import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Collab from "./components/Collab";

//seo
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-teal-50">
        <Navbar />
        <main className="mt-32 px-8 md:px-16 lg:px-32 xl:px-36 2xl:px-96 ">
          {children}
        </main>
        <Collab />
        <Footer />
      </body>
    </html>
  );
}
